### PR TITLE
this installs the new javaagent, while leaving some of the old agent around

### PR DESCRIPTION
**Pull request by jmazzitelli**
The old agent isn't installed/running, but the old download and installer zip files are available. The new javaagent is installed and running.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
do not merge this yet. it is here to test the new agent on the new inventory. At this time, it appears there are problems with the agent's inventory rest requests.

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jotak** [comment]
I've built it with current hawkular-agent and, at least for the inventory REST API, it seems to work well. I haven't tested the command gateway.

If someone is interested, I've pushed the corresponding docker image on my account: `jotak/hawkular-services:0.40.0.Final-SNAPSHOT`

**Comment by jmazzitelli** [comment]
no more SNAPSHOT dep. Can someone merge this?

**Pull request merged**
