### PR TITLE
HAWKULAR-1188 Event on Server addition or removal

### PR DESCRIPTION
**Pull request by jshaughn**
Listen for Inventory events creating or removing servers. Note there
are several server resource types, WildFly Server, Host Controller,
etc...

Refactored a bit now that we have different sorts of inventory
events generating server-side work and multiple listeners generating
Events for MIQ consumption.

### CODE REVIEW

**Comment by jshaughn** [comment]
@pilhuhn The screenshot below shows what I have here.   I need to know if this satisfies the requirement.  Because these are not representing an alert or failure I made these *detail* level events (not summary), so they only show if you click the checkbox. There are links to the provider and to the server resource.

hawkular-1188

**Comment by jshaughn** [comment]
@pilhuhn Note, To do this I used the generic "hawkular_event" that I already have defined in MIQ.  So, there is no MIQ side work/coordination involved.

**Comment by jshaughn** [comment]
@pilhuhn Nudge...

**Comment by pilhuhn** [comment]
LGTM - especially that those magically show up in MiQ

**Pull request merged**
