### PR TITLE
Provide docker-compose file at project root

### PR DESCRIPTION
**Pull request by jotak**
I think it's always a good point to provide a docker-compose file to quickly start any software :)

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by pilhuhn** [comment]
There is already a docker-compose template in docker-dist/ before accepting this PR we should figure out what to do with that template, so that there is only one place to maintain.

**Comment by jotak** [comment]
Ah right, I searched for "docker-compose.yml" and the other one is named differently. Is there a specific reason for not naming it docker-compose.yml?

**Comment by pilhuhn** [comment]
I guess I did it that way to illustrate it, but not to mandate how to do it (so people could/should modify to match their local need)

**Comment by jotak** [comment]
Ok. Then it's up to you for what we do about this PR. An advantage I would see in renaming the file, is that it makes it clear that it can be used as is, whereas with the current name my first idea is that it's a template file used for some build step in the maven process and I wouldn't be sure it can be used unless I have a closer look at it. (I admit it's not a big deal, except for lazy people :) )

**Comment by pilhuhn** [comment]
@jshaughn wdyt?
@jotak If Jay agrees, then update your pr to remove the -template one.

**Comment by jshaughn** [comment]
@pilhuhn @jotak, I think we should just have a clear docker-compose.yml file.  No one will be using this stuff other than us, it's not so much for public consumption but rather for what will make our lives easier.

**Comment by jshaughn** [comment]
@jotak, so do you want to update the PR and also fix the license issue?  We can then probably move forward and merge.

**Comment by jotak** [comment]
@jshaughn done

**Comment by jshaughn** [comment]
Thanks @jotak, I created HAWKULAR-1235 for this task.

**Pull request merged**
