### PR TITLE
Updated inventory model

### PR DESCRIPTION
**Pull request by jotak**
related to https://github.com/hawkular/hawkular-commons/pull/151 and https://github.com/hawkular/hawkular-commons/pull/154

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jmazzitelli** [comment]
LGTM

**Comment by jpkrohling** [comment]
ok to test

**Comment by jshaughn** [comment]
This seems OK to merge. Merging, and then creating new hawkular-1259 branch.

**Pull request merged**
