### PR TITLE
HAWKULAR-1138 move to okhttp 3.x

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by Jiri-Kremser** [comment]
If I run the itests on this PR with parent-pom built as snapshot (this [PR](https://github.com/hawkular/hawkular-parent-pom/pull/94)),
it builds, but I got the runtime error during the tests:
```
[ERROR] Caused by: java.lang.NoClassDefFoundError: com/squareup/okhttp/Credentials
[ERROR] at org.hawkular.cmdgw.ws.test.ClientConfig.<clinit>(ClientConfig.java:32)
```

**Comment by jmazzitelli** [comment]
@Jiri-Kremser you need to also build hawkular-commons with the new stuff. It is not enough to just build parent-pom and get this to work.

**Comment by Jiri-Kremser** [comment]
> you need to also build hawkular-commons with the new stuff. It is not enough to just build parent-pom and get this to work.

right, so far everything is `-snapshot`

**Comment by jmazzitelli** [comment]
note: those snapshot versions will not make it into master branches - I will eventually be removing from my PRs those snapshot versions once things start getting released in the proper order.

**Comment by Jiri-Kremser** [comment]
with hawkular-comons built with this [PR](https://github.com/hawkular/hawkular-commons/pull/94) + everything glued together via snapshots and local mvn repo, I got this during the tests:

http://pastebin.com/afT0f3Uy

.. a lot of retries to get some resource from inventory and it fails with 

```
FAILED: agentDiscoverySuccess
java.lang.AssertionError: No success getting [org.hawkular.services.rest.test.TestClient$TestResponse$$Lambda$36/1714378342@dcfda20] after trying [500] times with delay [1000] ms
```

there were also following lines in the log:

```
WARNING: A connection to http://127.0.0.1:8080/ was leaked. Did you forget to close a response body?
```

I guess, it's better to wait for all the other PRs to be merged, because this one depends on them

**Comment by Jiri-Kremser** [comment]
I guess, it's (^) because there is also a PR to agent https://github.com/hawkular/hawkular-agent/pull/278

**Comment by jmazzitelli** [comment]
I'm getting this too

```
metricsUp(org.hawkular.services.rest.test.MetricsAlertingITest)  Time elapsed: 25.49 sec  <<< FAILURE!
java.lang.AssertionError: No success getting [org.hawkular.services.rest.test.TestClient$TestResponse$$Lambda$27/1860886124@4a891c97] after trying [50] times with delay [500] ms
	at org.hawkular.services.rest.test.TestClient$Retry.retry(TestClient.java:85)
	at org.hawkular.services.rest.test.TestClient$TestResponse.assertWithRetries(TestClient.java:224)
	at org.hawkular.services.rest.test.MetricsAlertingITest.metricsUp(MetricsAlertingITest.java:53)
```

This is going to have to be fixed.

**Comment by jmazzitelli** [comment]
I think its because the timeouts aren't long enough - the tests should wait longer. I'm seeing this as the cause:

> Caused by: java.lang.AssertionError: expected [STARTED] but found [STARTING]

**Comment by jmazzitelli** [comment]
This is failing for some unknown, odd reason. This all passes locally for me:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:50 min
```

**Comment by jmazzitelli** [comment]
Even though this is green, this is an error that is occurring repeatedly:

```
Caused by: javax.ejb.EJBException: java.lang.ClassCastException: org.hawkular.alerts.api.services.DefinitionsService$$$view16 cannot be cast to org.hawkular.alerts.api.services.DefinitionsService
```

**Comment by jshaughn** [comment]
LGTM. Note that the metrics version is still older, the release does not incorporate the updated commons.  And the alerts email plugin is tied to the version of alerts embedded in metrics.  If we see any issues between components and metrics we may need to revisit the version of metrics in use.

**Pull request merged**
