### PR TITLE
HAWKULAR-1245 Hand over public key in pem format to make it easier to trust this Hawkular-services

### PR DESCRIPTION
**Pull request by josejulio**
When letting the dockerized hawkular-services to start on SSL mode and auto-generate the key-pair, you had to fetch the public certificate from the server, making it more complicated to run a few tests on it.
By proving means to hand the certificate, is easier to demo (see [this](https://github.com/hawkular/hawkular-agent/pull/346/files#diff-7a07ec50f481a0ac432371e84fb19d21R55)) or easier with a docker-compose (todo)

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jshaughn** [comment]
@josejulio This PR has been sitting for a while, is it still ingood shape to merge?  If so, please create an associated hawkular jira so we can track changes to services.  Let me know if that is done and then I can merge.

**Comment by josejulio** [comment]
Still need to check something with https://github.com/hawkular/hawkular-agent/pull/346

**Comment by josejulio** [comment]
Rebased and created the JIRA

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jshaughn** [comment]
@josejulio What is the status of this PR?  Is it still something you want merged?

**Comment by josejulio** [comment]
I don't think this is needed, I'll close it and re-open if is really needed.

**Pull request closed without merging**
