### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jmazzitelli** [comment]
@lucasponce  or @jotak - take a look at the build failure here. I do NOT see this locally - builds fine for me and the server works. But travis is producing the following error:

23:57:41,181 ERROR [org.jboss.as.ejb3.invocation] (ServerService Thread Pool -- 64) WFLYEJB0034: EJB Invocation failed on component InventoryConfig for method public java.nio.file.Path org.hawkular.inventory.service.InventoryConfig.getConfigPath(): javax.ejb.ConcurrentAccessTimeoutException: WFLYEJB0241: EJB 3.1 PFD2 4.8.5.5.1 concurrent access timeout on InventoryConfig - could not obtain lock within 5000MILLISECONDS

**Comment by lucasponce** [comment]
ok, I take this

**Comment by jshaughn** [comment]
Marking DNM because I'm not sure the labeling is working correctly with these src-deps.  This has nothing to do with the build failure reported above.  A travis restart resulted in green.

**Comment by lucasponce** [comment]
@jshaughn started to look at it.
Locally, it passes, so probably as @jshaughn says, travis error is not related due a problem in the code.

**Comment by jshaughn** [comment]
I didn't look at it.  I just hit the restart build button to see if it pass.  @lucasponce do we need to now add comments whenever we restart a travis build?

**Comment by jshaughn** [comment]
removing DNM label. My issue is because I wasn't starting P with the correct config to get the 'feed_id' label applied server-side.

**Pull request merged**
