### PR TITLE
correct hawkular-service image address in docker-compose-template

### PR DESCRIPTION
**Pull request by garg-anuj**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by garg-anuj** [comment]
reference

https://hub.docker.com/r/hawkular/hawkular-services/
`docker pull hawkular/hawkular-services`

**Comment by garg-anuj** [comment]
Somehow I am not able to squash these commits. So if this unacceptable as unformatted then someone can close this PR and add this change in any future PR

**Comment by pilhuhn** [comment]
Good catch. Thanks for this.

**Pull request merged**
