### PR TITLE
Configure travis to push to docker hub for each tag

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by pilhuhn** [comment]
Shouldn't we do that from Jenkins and only when a release is done?

**Comment by pilhuhn** [comment]
Mvn is unhappy with bad/missing license in `.travis.docker-push.sh`

**Comment by pgier** [comment]
Updated the Jenkins configuration to do the push, so this PR is no longer needed.

**Pull request closed without merging**
