### PR TITLE
Fixing github call for bot.

### PR DESCRIPTION
**Pull request by josejulio**
~~DO NOT MERGE (yet)~~

### CODE REVIEW

**Comment by josejulio** [comment]
Is OK to review and merge now.

**Comment by pilhuhn** [comment]
Are you sure that this Heroku thingy is reliable? What happens when it is down?

**Comment by josejulio** [comment]
It won't report the gem status if is down. (e.g. no @hawkular-bot message).
If needed, I could change from heroku to somewhere else.

**Comment by josejulio** [comment]
As for if its reliable. I can't guarantee that it won't be down, as I'm using a free account.

**Pull request merged**
