### PR TITLE
hawkular-1275 master rebase

### PR DESCRIPTION
**Pull request by jmazzitelli**
This rebases the hawkular-1275 branch on master to keep it up to date and avoid having to resolve conflicts later.

### CODE REVIEW

**Comment by jshaughn** [comment]
@jmazzitelli , I'm not sure about this work, the rebase was already done when I created this branch.  Something seems fishy here.

**Comment by jotak** [comment]
Maybe a merge would make more sense, so that we know exactly which commits are added here?

**Comment by jshaughn** [comment]
OK, I think the issue here is on my side.  I actually did most or all of this already, locally, but it seems I didn't get it into origin, not sure how I managed to do that :(   Anyway, +1 @jotak, we won't squash this, we'll just merge.  I'll do it now.

**Comment by jotak** [comment]
Hmm when I wrote about "merge", I meant `git merge upstream/master` instead of `git rebase upstream/master`, it was not about how to submit this PR. Now git history show duplicated commits: the ones from the rebased branch and the ones from the not-rebased branch. It's a minor thing for sure, but next time we should consider doing `git merge`.

**Comment by jshaughn** [comment]
ugh. sorry.

**Comment by jmazzitelli** [comment]
For the record:

The reason for this PR was because there were conflicts in something that went into master recently. I wanted to rebase now and clear them up while I remembered how to resolve the conflicts. 

The conflicts only dealt with the openshift template files (1275 branch removed the C* stuff, master still has them, and those C* templates in master changed recently - so the conflict resolution was just me having to remove those C*-related things again.

**Pull request merged**
