### PR TITLE
Support Metrics Hawkular-Admin-Token

### PR DESCRIPTION
**Pull request by vnugent**
Tested ephemeral template on OSE 3.5

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jshaughn** [comment]
@vnugent , @pilhuhn, @mwringe, Looking at the issue related to this PR, [135], I'm not sure it makes sense to use h-services as a general purpose metrics server.  h-services is pretty much used as a single-tenant system (tenant 'hawkular').  Origin-metrics (a hawkular-metrics deployment) already exists in OS, maybe that makes more sense for you to use?

I'm going to mark this as DoNotMerge while this is discussed.

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by mwringe** [comment]
Closing old issues while we move the master to another branch.

**Pull request closed without merging**
