### PR TITLE
Provide an explicit Dockerfile and modified standalone.conf.

### PR DESCRIPTION
**Pull request by pilhuhn**
Also chown the dirs to jboss.

This later step may not be needed if the base image already does this.

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
When Openshift runs the container, it doesn't take into consideration the user that is defined in the dockerfile, but it uses 'random' UID. The UID range can be set per project by setting the openshift.io/sa.scc.uid-range metadata annotation, but by default we can assume it's pretty much random.

So chowning everything to jboss user doesn't help us.

this is what the OS online course says:

In a pure Docker environment, simple Dockerfiles may generate images that fail to run in OSE 3. Most of the time, this is because the image needs to run as root or some other fixed UID. But OSE runs containers using a random UID. The fix is making sure folders written to while running the container have a+rwx permissions.

**Comment by pgier** [comment]
I like having the explicit Dockerfile vs. the auto-generated one.  One negative though  is that we can no longer parameterize the base image name and other info.  I submitted a PR to the docker-maven-plugin (https://github.com/fabric8io/docker-maven-plugin/pull/686) to allow variable substitution in the Dockerfile, so hopefully with a future release of the plugin we can more easily switch out the base image.

**Comment by Jiri-Kremser** [comment]
lgtm, the travis went crazy, but I was able to build it locally and use it in openshift with the `openshift/origin-metrics-cassandra:v1.4.1` as C* image and it works like a charm

**Comment by pilhuhn** [comment]
I think this bombs on travis as the used `docker-compose.yml` file has no volume defined for the data directory.
```
volumes:
    - /tmp/opt/hawkular/server:/opt/data
```
(But that is more or less a guess)

**Comment by pilhuhn** [comment]
Travis is now (almost) happy after the volume has been added. There are still 2 failures where operations fail, but inside container they would not be expected to work anyway.

Merging this now.

**Pull request merged**
