### PR TITLE
Init InventoryService with backend/ispn stub

### PR DESCRIPTION
**Pull request by jotak**
Needs this [1] in order to compile.
For the time being hawkular-services doesn't have dependency management in parent pom, I don't know if it's intentional... 

[1] https://github.com/hawkular/hawkular-services/pull/180

### CODE REVIEW

**Comment by lucasponce** [comment]
I wonder if we can consolidate the inventory API in hawkular-services too.
It seems we won't need a separate component as potential agent code could live here too.
What do you think @jotak ?
Then in the first steps we can avoid to release commons or using srcdeps.

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jotak** [comment]
@lucasponce +1 I'll move the model

**Comment by jotak** [comment]
Closing, I'll open another one

**Comment by jshaughn** [comment]
> I wonder if we can consolidate the inventory API in hawkular-services too.
It seems we won't need a separate component as potential agent code could live here too.

That has been my assumption all along, but to make it clear, yes. I thing Inventory will be a native part of hServices/MWM.  If the "agent" is also central/native then interaction will be local.

**Pull request closed without merging**
