### PR TITLE
Add optional cassandra timeout check when starting container

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by jshaughn** [comment]
@pgier license checker issue...

**Comment by pgier** [comment]
@jshaughn thanks, should be fixed now

**Comment by jshaughn** [comment]
@pgier Could you create a hawkular jira for this, I'm trying to get us to track services changes a little more formally.  Just add a short note as to whether this was a bug fix, an enhancement you found useful, etc.  Thanks!

**Comment by pgier** [comment]
Finally got around to creating a jira for this: https://issues.jboss.org/browse/HAWKULAR-1244

**Comment by FilipB** [comment]
retest this please

**Comment by jshaughn** [comment]
Ignoring perf-stability-test failure, looks travis related.  Thanks @pgier .

**Pull request merged**
