### PR TITLE
HAWKULAR-1246 - Adds user and password to management realm

### LINKED ISSUE #172: Hawkular Agent unable to connect to hawkular services on Openshift
I created a hawkular services instance on Openshift using a "standard" configuration (https://github.com/hawkular/hawkular-services/blob/master/openshift/hawkular-services-ephemeral.yaml)

It appears the Hawkular Agent is not starting on the Openshift 

`21:19:03,610 INFO  [org.hawkular.agent.monitor.service.AgentCoreEngine] (Hawkular Java Agent Start Thread) HAWKMONITOR010000: Starting Hawkular Agent`

`21:19:29,461 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (Hawkular Java Agent Start Thread) HAWKMONITOR010039: The command-gateway URL is [wss://127.0.0.1:8443/hawkular/command-gateway/feed/hawkular-services-2-sh9vg]`

` 21:19:29,503 INFO  [org.hawkular.agent.monitor.scheduler.SchedulerService] (Hawkular Java Agent Start Thread) HAWKMONITOR010012: Starting scheduler`

`21:19:29,512 INFO  [org.hawkular.agent.monitor.protocol.ProtocolServices] (Hawkular Java Agent Start Thread) HAWKMONITOR010019: Managed server [Local DMR] is disabled. It will not be monitored `

`21:19:29,571 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp https://127.0.0.1:8443/...) HAWKMONITOR010034: Opened feed WebSocket connection to endpoint [wss://127.0.0.1:8443/hawkular/command-gateway/feed/hawkular-services-2-sh9vg]`

`21:19:30,555 INFO  [org.hawkular.agent.monitor.protocol.EndpointService] (Hawkular Java Agent Start Thread) Endpoint [DMREndpointService[Endpoint[Local]:[https-remoting://127.0.0.1:9993]]] is not ready yet - will wait`

[Full Log](https://paste.fedoraproject.org/paste/-WMtDG17pEcxwZnIcgWDGg)

I am using standard username/password (`username=jdoe` and `password=password`).

I talked with @josejulio and @jmazzitelli, it seems to be ok docker container and it is more related to openshift.

Best Regards,
Guilherme Baufaker Rêgo

### PR DESCRIPTION
**Pull request by josejulio**
User on management realm seems to be required when deploying on openshift.

Fixes #172

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by josejulio** [comment]
@jmazzitelli can you please check?

**Comment by jmazzitelli** [comment]
Does this mean the agent needs to be told the username/password in its local-dmr / remote-dmr configuration ?

**Comment by josejulio** [comment]
Actually those are set in the javaagent config. I wonder if for that reason it isn't connecting...

**Comment by jmazzitelli** [comment]
> Actually those are set in the javaagent config. I wonder if for that reason it isn't connecting...

Ha! So the agent was already told to use those username/password credentials? Well, then that explains the error! The agent was sending over username/password which weren't defined in the server and thus why the server didn't allow the connection.

**Comment by josejulio** [comment]
Still... it doesn't explain why it was working on a regular docker... plus I got a shell on the pod, tried using jboss-cli and couldn't connect without user/password.

**Comment by josejulio** [comment]
I did a hawkular-services build [1] without username/password on the remote-dmr.
It still is stuck on:
```
00:03:04,161 INFO  [org.hawkular.agent.monitor.protocol.EndpointService] (Hawkular Java Agent Start Thread) Endpoint [DMREndpointService[Endpoint[Local]:[https-remoting://127.0.0.1:9993]]] is not ready yet - will wait
```

There is no management-user, only application user.
Adding a management user doesn't do anything, (its trying to connect without user/pass)

So for some reason you do require an username on that environment.

[1] 0.40.0.Final-SNAPSHOT https://hub.docker.com/r/josejulio/hawkular-services/tags/

**Comment by jmazzitelli** [comment]
This LGTM however, why does hawkular-bot say this might fail with ruby client?

**Comment by josejulio** [comment]
Because of this:
https://travis-ci.org/hawkular/hawkular-services/builds/264848855#L3950
It looks like this issue: https://github.com/hawkular/hawkular-client-ruby/issues/201
So i would say that is safe to ignore that error.

**Comment by jmazzitelli** [comment]
OK, merging this because we need it. We'll let the ruby client issue be fixed later.

**Pull request merged**
