### PR TITLE
Update Metrics hash to fix /status and /static/* requiring auth.

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by ppalaga** [comment]
Now after #3 was merged, there is a test checking `/metrics/status`: https://github.com/hawkular/hawkular-services/blob/master/itest/src/test/java/org/hawkular/services/rest/test/MetricsITest.java#L50

As it statnds now, the client send an Auth header. Should we not change the test to send the request without Auth header?

**Comment by jpkrohling** [comment]
Merge after #8

**Comment by jpkrohling** [comment]
Actually, I'll close this one. Moving to Metrics `0.16.0` would be a better option at this point.

**Comment by ppalaga** [comment]
@jpkrohling , FYI, me and @stefannegrea agreed that the itests in services accessing `/status` should do so without both Auth and Tenant headers.

**Comment by jpkrohling** [comment]
Absolutely, it makes sense.

**Pull request closed without merging**
