### PR TITLE
HAWKULAR-1121 Fix wrong path on MetricsAlerting itest

### PR DESCRIPTION
**Pull request by lucasponce**
This PR needs a release of metrics and alerting.
The bug on the itest masked some issues on the intregation side.

I will update the PR once these releases are out.

Please don't merge as pom.xml is provisional.

### CODE REVIEW

**Comment by lucasponce** [comment]
This one depends on https://github.com/hawkular/hawkular-metrics/pull/600, https://github.com/hawkular/hawkular-metrics/pull/601, and https://github.com/hawkular/hawkular-alerts/pull/203
Also, new releases are necessary to include those fixes.

**Comment by lucasponce** [comment]
Updated pom.xml with metrics 0.19.2.Final and alerting 1.1.4.Final

**Comment by lucasponce** [comment]
/cc @stefannegrea @jshaughn 
This fix is ready to merge unless there are any other issue.

**Comment by jshaughn** [comment]
@lucasponce Sorry, I don't have permission to merge.

**Pull request merged**
