### PR TITLE
Next version of HAM

### PR DESCRIPTION
**Pull request by jshaughn**
Email action plugin now packaged in the metrics ear.

### CODE REVIEW

**Comment by jshaughn** [comment]
This has snapshots and needs to be updated to release versions when appropriate.

**Comment by jshaughn** [comment]
@stefannegrea Just to let you know that this PR already exists in preparation of the Metrics 0.22.0.Final release.  When the release is made, I can update this PR to the final metrics version.

**Comment by stefannegrea** [comment]
@jshaughn, Hawkular Metrics 0.22.0 is not meant to be used with Hawkular Services.

**Comment by jshaughn** [comment]
@stefannegrea Why not?  This is an issue we need to work on,  we should try and prevent having metrics' packaging block alerting features for Hservices.  So what version is targeted for Hservices?

**Comment by jshaughn** [comment]
@stefannegrea I moved this to go against 0.23.0.Final, when released

**Comment by pilhuhn** [comment]
retest this please

**Comment by FilipB** [comment]
This PR is ready to be merged from performance point of view. It brings performance improvements up to 6%.

**Comment by pilhuhn** [comment]
retest this please

**Comment by josejulio** [comment]
FYI the following tests are failing on the hawkular-client-ruby.

```
1) Alert/Triggers Should get the action definitions
     Failure/Error: expect(ret['email'].size).to be(7)
       expected #<Fixnum:15> => 7
            got #<Fixnum:17> => 8
```
If the size of the returned attributes increased we might need to update the test accordingly.

```
2) NonSecure Operation/Operation Restart should be performed and eventually respond with success
     Failure/Error: expect(actual_data['status']).to eq('OK')

Could not perform [Restart Deployment] on a [Application] given by inventory path [/t;hawkular/f;1d4a474a-f977-48ba-b7bf-b32557d19a9c/r;Local~~] requested on [2017-01-27T18:48Z]: org.hawkular.dmrclient.FailureException: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => "WFLYCTL0216: Management resource '[(\"deployment\" => \"hawkular-alerts-actions-email.war\")]' not found"}}
```

And we might have to stop using `hawkular-alerts-actions-email.war` on ruby-client tests.

**Comment by jshaughn** [comment]
@josejulio I created https://github.com/hawkular/hawkular-client-ruby/pull/183 to hopefully solve the failures.  The tests needed to be updated to be compatible with the changes introduced by the PR.

**Comment by jshaughn** [comment]
@pilhuhn Please merge this.  There is another PR that updates the ruby client specs to be compatible with these changes. We'll merge that after this goes in.  And the perf failure is due to increased perf, not decreased.

**Pull request merged**
