### PR TITLE
support agent extension for EAP6

### PR DESCRIPTION
**Pull request by jmazzitelli**
do not merge until https://github.com/hawkular/hawkular-agent/pull/280 gets into the agent master branch

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jmazzitelli** [comment]
Once https://github.com/hawkular/hawkular-agent/pull/280 is merged into master, the agent needs to be released at which time we can then merge this PR

**Comment by jmazzitelli** [comment]
I'm in the process of releasing 0.26.0.Final of the agent - once complete, I'll rerun this build and when it goes green this PR can be merged

**Comment by jmazzitelli** [comment]
@pilhuhn  I did not change anything related to hawkular-client-ruby in this PR. I just deployed the eap6 wf-extension zip in the server so the download servlet can serve it to the installer, and bumped up the agent version.

Someone should check to see what's going on with the "This PR potentially fails with hawkular-client-ruby." warning - if its all OK, this needs to be merged in order to get EAP6 support.

**Comment by josejulio** [comment]
@jmazzitelli This is actually failing:

```
............................................................................................................error callback was called, reason: Could not perform [Restart Deployment] on a [Application] given by inventory path [/t;hawkular/f;7076c33e-8611-4fdb-a681-d7eb872df785/r;Local~~] requested on [2017-01-25T00:44Z]: org.hawkular.dmrclient.FailureException: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./hawkular/wildfly-agent" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./hawkular/wildfly-agent: javax.servlet.ServletException: Missing Hawkular WildFly Agent module download files
    Caused by: javax.servlet.ServletException: Missing Hawkular WildFly Agent module download files
    Caused by: java.io.FileNotFoundException: Cannot find agent download file [hawkular-wildfly-agent-wf-extension-eap6.zip] in: /opt/jboss/wildfly/standalone/configuration"}}}}
F....................................
Failures:
  1) NonSecure Operation/Operation Restart can be run multiple times in parallel
     Failure/Error: expect(actual_data['status']).to eq('OK')
       expected: "OK"
            got: nil
       (compared using ==)
     # ./spec/integration/operations_spec.rb:409:in `block (4 levels) in <module:RSpec>'
     # ./spec/spec_helper.rb:242:in `block in record_websocket'
     # ./spec/spec_helper.rb:284:in `block in record_websocket_cassette'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/simple-websocket-vcr-0.0.7/lib/simple_websocket_vcr.rb:82:in `use_cassette'
     # ./spec/spec_helper.rb:283:in `record_websocket_cassette'
     # ./spec/spec_helper.rb:250:in `record_websocket'
     # ./spec/integration/operations_spec.rb:155:in `block (4 levels) in <module:RSpec>'
```

After running all the tests on hawkular-services (and getting the passed status) I run this script (see on travis log, line 2222) [.travis.hawkular-client.ruby.sh](https://github.com/jmazzitelli/hawkular-services/blob/d12ca3bfcbca91a10d0e6770e1167808d2e8d339/.travis.hawkular-client.ruby.sh)
It builds Hawkular-services again with `-Pdev,dozip` flags and then does a docker-build which uses to run hawkular-client-ruby tests against it.

Maybe we need to update something on docker or the script?

**Comment by jmazzitelli** [comment]
Interesting, so this is related to this PR. That -eap6.zip is the new EAP6-specific extension that needs to go into the configuraiton direction so the download servlet can access it.

**Comment by jmazzitelli** [comment]
OK, I think I fixed the issue. Had to add the new -eap6 file to the docker build. See: https://github.com/hawkular/hawkular-services/pull/110/files#diff-45e6307ed7e5a6d6e486fce7dc915070

Let's see if the warning goes away after this upcoming travis build.

**Comment by jmazzitelli** [comment]
Looks like all is well now. This can be merged.

**Pull request merged**
